#!/bin/bash
#usage=$(mpstat 1 1 | awk '/Average/ {print $12}' | cut -d "." -f 1 | cut -d "," -f 1)
usage=$(top -bn1 | awk '/%Cpu/ {print $2}')
#temp=$(sensors | grep Package | awk '{print substr($4, 2)}')
temp=$(($(cat /sys/class/thermal/thermal_zone0/temp)/1000))
echo  $usage% $temp°
