#!/bin/bash
case $BLOCK_BUTTON in
    1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
    [2-9]) echo $BLOCK_BUTTON
      ;;
esac

echo  $(free -h | awk '/Mem:/ { gsub(/i/, ""); print $3 }')
