#!/bin/bash
state=.config/i3blocks/state/music
if [ -f $state ]; then
  test "$BLOCK_BUTTON" = "1" && rm $state
else
  test "$BLOCK_BUTTON" = "1" && touch $state
fi 

if [ -f $state ]; then
  music=$(mpc -f "[%artist% - ]%title%" | awk 'NR==      1' | tr -d '\"'})
  echo ♫ $music
else
  echo ♫
fi
